# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package valustor;
use base qw(Exporter);
use base qw(DynaLoader);
package valustorc;
bootstrap valustor;
package valustor;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package valustor;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package valustor;


############# Class : valustor::ValuStorWrapper ##############

package valustor::ValuStorWrapper;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( valustor );
%OWNER = ();
*retrieve = *valustorc::ValuStorWrapper_retrieve;
*store = *valustorc::ValuStorWrapper_store;
*close = *valustorc::ValuStorWrapper_close;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


############# Class : valustor::ValuStorNativeWrapper ##############

package valustor::ValuStorNativeWrapper;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( valustor );
%OWNER = ();
*retrieve = *valustorc::ValuStorNativeWrapper_retrieve;
*store = *valustorc::ValuStorNativeWrapper_store;
*close = *valustorc::ValuStorNativeWrapper_close;
sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package valustor;

1;
