/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_VALUSTOR_H
#define PHP_VALUSTOR_H

extern zend_module_entry valustor_module_entry;
#define phpext_valustor_ptr &valustor_module_entry

#ifdef PHP_WIN32
# define PHP_VALUSTOR_API __declspec(dllexport)
#else
# define PHP_VALUSTOR_API
#endif

ZEND_NAMED_FUNCTION(_wrap_ValuStorWrapper_retrieve);
ZEND_NAMED_FUNCTION(_wrap_ValuStorWrapper_store);
ZEND_NAMED_FUNCTION(_wrap_ValuStorWrapper_close);
ZEND_NAMED_FUNCTION(_wrap_ValuStorNativeWrapper_retrieve);
ZEND_NAMED_FUNCTION(_wrap_ValuStorNativeWrapper_store);
ZEND_NAMED_FUNCTION(_wrap_ValuStorNativeWrapper_close);
PHP_MINIT_FUNCTION(valustor);

#endif /* PHP_VALUSTOR_H */
